config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root 'sessions#home'

  resources :foods
  resources :meals do 
    resources :foods, only: [:new, :create]
    resources :foodlogs, only: [:edit, :update]
  end
  resources :foodlogs
  resources :users, only: %i[new create edit show update destroy] do 
    resources :meals, only: %i[index show]
  end

  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  
  delete '/logout', to: 'sessions#destroy'

  # custom route for scoped items
  # get 'meals/fatty', to: 'meals#fatty', as: 'fatty_meal'

  # match '/auth/:provider/callback', to: 'sessions#create', via: [:get, :post]
  get '/auth/:provider/callback', to: 'sessions#omniauth'
 
  get '*path', to: redirect { '/' }

end

app/models/meal.rb
class Meal < ApplicationRecord
    # t.string :name

    belongs_to :user
    has_many :foodlogs, dependent: :destroy
    has_many :foods, through: :foodlogs, dependent: :destroy

    validates :name, presence: true
    validates :name, inclusion: { in: ["Breakfast", "Lunch", "Dinner", "Snack", "Drink"] }

    scope :order_by_calories, -> { order(price: :desc)}
    scope :order_by_carbs, -> { order(carbs: :desc)}

    # extend Search::ClassMethods

    def foodlogs_attributes=(foodlogs_attributes)
        foodlogs_attributes.values.each do |foodlog_attributes| 
            next unless foodlog_attributes[:quantity].present?
            foodlog = Foodlog.find_or_create_by(foodlog_attributes)
            self.foodlogs << foodlog
        end	  
    end

    def foods_attributes=(foods_attributes)
        foods_attributes.values.each do |food_attributes| 
            # {"quantity"=>"1", "food_id"=>"8"}
            next unless food_attributes.values.all? { |v| v.present? }
            food = Food.find_or_create_by(food_attributes)
            self.foods << food
        end	  
    end


    def todays_meals
        Meal.all.today
    end

    def pretty_date
        self.created_at.strftime("%A, %d %b %Y %l:%M %p")
    end

    def short_date
        self.created_at.strftime("%b %d, %Y")
    end

    def self.today 
        where("created_at >= ?", Time.now.beginning_of_day) 
    end


    def self.meals_total
        mealcount = 0
        self.each {|meal| mealcount += meal.calculate_macros}
        mealcount
    end

    # Today.where(created_at: (Time.now.midnight - 1.day)..Time.now.midnight)

    # Author.joins(:articles).where(articles: { author: author })

    def calculate_macros(macro = :calories)
        count = 0
        self.foodlogs.each do |foodlog|
            item = foodlog.quantity * foodlog.food.send(macro)
            count += item
        end
        count
    end

    #view example
    # @meal.order_by_calories.order_by_carbs(15)
end

app/controllers/meals_controller.rb
class MealsController < ApplicationController

  before_action :require_login
  before_action :find_meals, only: [:edit, :update, :destroy]
  before_action :redirect_if_not_owner,  only: [:update, :destroy]


  def new
    if params[:food_id] && @food = Food.find_by_id(params[:food_id])
      @meal = @food.meals.build
      @foodlog = @food.foodlogs.build
    else
      @meal = Meal.new
    end
  end

  def create
    meal = current_user.meals.build(meal_params)
    if meal.valid?
      meal.save

      redirect_to meal_path(meal)
    else
      @meal = Meal.new
      render :new
    end
  end

  def index
    #nested route
    if params[:user_id] && @user = User.find_by_id(params[:user_id])
        @meals = @user.meals
    else
      @meals = current_user.meals
      # @meals = Meal.all 
    end
  end

  def show
    @meal = Meal.find_by_id(params[:id])
    # @meal = @foodlog.meal
    @foodlog = @meal.foodlogs.find_by_id(params[:id])
    @foods = Food.all.order_by_name
    @food = @meal.foods.build
    #don't need
    @foodlogs = @meal.foodlogs
  end

  def edit
    @meal = current_user.meals.find_by_id(params[:id])
  end

  def update
    @meal.update(meal_params)
    
    redirect_to meal_path(@meal)
  end

  def destroy
    @meal.foodlogs.destroy
    @meal.destroy
    redirect_to meals_path
  end

    
  private

  def meal_params
    params.require(:meal).permit(
      :name, 
      # foods_attributes: [:name, :category, :carbs, :fats, :proteins, :calories], 
      foodlogs_attributes: [:quantity, :meal_id, :food_id])
  end

  def find_meals
    @meal = current_user.meals.find_by_id(params[:id])
  end

  def redirect_if_not_owner
      if @meal.user != current_user
          redirect_to user_path(current_user), alert: "You can't edit this meal!"
      end
  end

end

app/helpers/meals_helper.rb
module MealsHelper

    # def calculate_calories
    #     @meal.foods.each do {
    #         calculate
    #     }
    # end



end

app/views/meals/_form.html.erb
<%= render partial:'/shared/errors', locals: {obj: @meal} %>

<%= form_for @meal do |f| %>
  <%= f.label :name %>
  <%= f.select :name, options_for_select(["Breakfast", "Lunch", "Dinner", "Snack", "Drink"], @meal.name) %>

  <%= f.submit %>
<% end %>

app/views/meals/edit.html.erb
<h1>Edit:</h1>

<%= render 'form' %>

<%= button_to "Delete Meal", meal_path(@meal), method: :delete, data: { confirm: 'Are you sure?' }%>

app/views/meals/index.html.erb
 <h2> All of the Meals </h2> 

 <%= link_to 'Create Meal', new_meal_path(@meal) %>

<ul>
  <% @meals.each do |meal| %>
    <li><%= link_to "#{meal.name} (#{meal.pretty_date})", meal_path(meal) %></li>

  <% end %>
</ul>

app/views/meals/new.html.erb
<h2>New:</h2>

<%= render 'form' %>

app/views/meals/show.html.erb
<h3><%= "#{@meal.name} (#{@meal.short_date})" %></h3>
<%= link_to 'Edit Meal', edit_meal_path(@meal) %>
<br>

 <ul>
    <li>Calories: <%# @meal.foodlogs.exists? ? @meal.meal_macros("calories") : "0" %>
    <%= @meal.foodlogs.exists? ? @meal.calculate_macros : "0" %></li>
    <li>Carbs: <%= @meal.foodlogs.exists? ? @meal.calculate_macros(:carbs) : "0" %></li>
    <li>Fats: <%= @meal.foodlogs.exists? ? @meal.calculate_macros(:fats) : "0" %></li>
    <li>Proteins: <%= @meal.foodlogs.exists? ? @meal.calculate_macros(:proteins) : "0" %></li>
</ul>

<br>

<h4>Food Logs: </h4>
<ul>
 <% @foodlogs.each do |log|%>
    <li><%= log.quantity %>x <%= log.food.name %><%= " - " %><%= link_to "Edit", edit_meal_foodlog_path(@meal, log) %><%= button_to("Delete", foodlog_path(log), method: 'delete' )%></li>
  <% end %>
</ul>


<% if  current_user.meals.include?(@meal) %>

<br>

<%= form_for @meal.foodlogs.build do |f| %>
  <%= f.hidden_field :meal_id%>
  <%= f.label :food_id, "Add Food: " %>

  <%= f.collection_select(:food_id, @foods, :id, :name)%> 

  <%= f.number_field :quantity, in: 1..20, step: 1, value: 1 %> <br>

  <%= f.submit %>
<% end %>

<br>

<%= link_to "Create New Food", new_meal_food_path(@meal)%>

<% end %>