config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root 'sessions#home'

  resources :foods
  resources :meals do 
    resources :foods, only: [:new, :create]
    resources :foodlogs, only: [:edit, :update]
  end
  resources :foodlogs
  resources :users, only: %i[new create edit show update destroy] do 
    resources :meals, only: %i[index show]
  end

  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  
  delete '/logout', to: 'sessions#destroy'

  # custom route for scoped items
  # get 'meals/fatty', to: 'meals#fatty', as: 'fatty_meal'

  # match '/auth/:provider/callback', to: 'sessions#create', via: [:get, :post]
  get '/auth/:provider/callback', to: 'sessions#omniauth'
 
  get '*path', to: redirect { '/' }

end

app/models/foodlog.rb
class Foodlog < ApplicationRecord
  # t.integer "quantity"
  # t.bigint "food_id", null: false
  # t.bigint "meal_id", null: false

  belongs_to :food
  belongs_to :meal

  validates :quantity, presence: true
  validates :quantity, numericality: { only_integer: true  }

  scope :order_by_popular, -> { order() }

  def log_macros(macro = :calories)
    self.quantity * self.food.send(macro)
  end

  def self.today 
    where("created_at >= ?", Time.now.beginning_of_day) 
  end

end

app/controllers/foodlogs_controller.rb
class FoodlogsController < ApplicationController

    before_action :require_login
    before_action :find_foodlogs, only: [:show, :edit, :update, :destroy]
    before_action :redirect_if_not_owner, only: [:edit, :update, :destroy]

    def new
        @foodlogs = Foodlog.new
    end
    
    def create
        meal = Meal.find_by_id(params[:meal_id])
        
        @foodlog = current_user.foodlogs.build(foodlog_params)
        if @foodlog.save
            redirect_to "/meals/#{@foodlog.meal_id}"
        else
            render "/meals/show", alert: "Foodlog must contain quantity"
        end
    end
    
    def index
        @foodlogs = Foodlog.all
    end

    def show

    end

    def edit
        @foods = Food.all.order_by_name
    end

    def update

        # if @foodlog = current_user.foodlogs.find_by_id(params[:id])
        #     foodlog.update(meal_params)
            
        #     redirect_to meal_path(@meal)
        # else
        #     render :new
        # end

        @foodlog.update(foodlog_params)
        
        redirect_to "/meals/#{@foodlog.meal_id}"
    end

    def destroy
        @foodlog.destroy
        redirect_to "/meals/#{@foodlog.meal_id}"
    end


    private

    def foodlog_params
        params.require(:foodlog).permit(:quantity, :meal_id, :food_id)
    end

    def find_foodlogs
        @foodlog = Foodlog.find(params[:id])
    end
    
    def redirect_if_not_owner
        if @foodlog.meal.user != current_user
            redirect_to user_path(current_user), alert: "You do not have permission to edit this"
        end
    end
end

app/helpers/foodlogs_helper.rb
module FoodlogsHelper
end

app/views/foodlogs/_form.html.erb
<%= render partial:'/shared/errors', locals: {obj: @foodlog} if @foodlog %>
<%= render partial:'/shared/errors', locals: {obj: @meal} if @meal %>

<%= form_for [@meal, @foodlog] do |f| %>
  <%= f.hidden_field :meal_id%>:
  <%= f.label :food_id, "Choose Food" %>:

  <%= f.collection_select(:food_id, @foods, :id, :name)%> 

  <%= f.number_field :quantity, in: 1..20, step: 1 %> <br>

  <%= f.submit %>
<% end %>

app/views/foodlogs/edit.html.erb
<h1>Edit:</h1>

<%= render 'form' %>

<%= button_to "Delete", foodlog_path(@foodlog), method: 'delete', data: { confirm: 'Are you sure?' } %>

app/views/foodlogs/show.html.erb
<h1>Foodlog</h1>
<ul>
  Food Quantities:
    <li><%= @foodlogs.quantity %>x <%= @foodlogs.food.name %><%= " - " %>
    
    <% if  current_user.foodlogs.include?(@foodlogs) %>
    <%= link_to "Edit", edit_foodlog_path(@foodlogs) %><%= button_to("Delete", foodlog_path(@foodlogs), method: 'delete' )%>
    <% end %>
    </li>
</ul>