config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root 'sessions#home'

  resources :foods
  resources :meals do 
    resources :foods, only: [:new, :create]
    resources :foodlogs, only: [:edit, :update]
  end
  resources :foodlogs
  resources :users, only: %i[new create edit show update destroy] do 
    resources :meals, only: %i[index show]
  end

  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  
  delete '/logout', to: 'sessions#destroy'

  # custom route for scoped items
  # get 'meals/fatty', to: 'meals#fatty', as: 'fatty_meal'

  # match '/auth/:provider/callback', to: 'sessions#create', via: [:get, :post]
  get '/auth/:provider/callback', to: 'sessions#omniauth'
 
  get '*path', to: redirect { '/' }

end

app/models/food.rb
class Food < ApplicationRecord
    # t.string :name
    # t.string :category
    # t.integer :carbs
    # t.integer :proteins
    # t.integer :fats
    # t.integer :calories

    belongs_to :user
    has_many :foodlogs
    has_many :meals, through: :foodlogs, dependent: :destroy

    validates :name, presence: true
    validates :name, uniqueness: true
    validates :category, inclusion: { in: ["Dairy", "Fruit", "Grain", "Oil", "Protein", "Vegetable", "Other"] }
    validates :calories, presence: true
    validates :calories, numericality: { greater_than_or_equal_to: 0}
    validates :carbs, :proteins, :fats, presence: true
    validates :carbs, :proteins, :fats, numericality: { greater_than_or_equal_to: 0}

    # accepts_nested_attributes_for :foodlogs

    # scope :order_by_name, ->  order(name:) 

    # scope :order_by_property, ->(num) { where('num < ? ', num) }
    scope :order_by_carbs, -> { order(carbs: asc) }
    scope :order_by_fats, -> { order(fats: asc) }
    scope :order_by_proteins, -> { order(proteins: asc) }

    extend Searchable::ClassMethods

    def self.order_by_name
        self.order(:name)
    end

    def foodlogs_attributes=(foodlogs_attributes)
        foodlogs_attributes.values.each do |foodlog_attributes| 
            # next unless foodlog_attributes[:quantity].present?
            next unless foodlog_attributes.values.all? { |v| v.present? }
            foodlog = Foodlog.find_or_create_by(foodlog_attributes)
            self.foodlogs << foodlog
        end	  
    end

    def meals_attributes=(meals_attributes)
        meals_attributes.values.each do |meal_attributes| 
            # {"quantity"=>"1", "meal_id"=>"8"}
            next unless meal_attributes.values.all? { |v| v.present? }
            meal = Meal.find_or_create_by(meal_attributes)
            self.meals << meal
        end	  
    end

end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController

  before_action :require_login
  before_action :find_foods, only: [:show, :edit, :update, :destroy]
  before_action :redirect_if_not_owner, only: [:edit, :update, :destroy]


  def new
    if params[:meal_id] && @meal = Meal.find_by_id(params[:meal_id])
        @food = @meal.foods.build
        @foodlog = @food.foodlogs.build
    else
        @food = Food.new
    end
  end

  def create
    @meal = Meal.find_by_id(params[:meal_id])
    food = current_user.foods.build(food_params)

    if food.valid?
      food.save
      if params[:meal_id] 
        redirect_to meal_path(@meal)
      else
        redirect_to food_path(food)
      end
    else
      @meal = Meal.find_by_id(params[:meal_id])
      @food = Food.find_by_id(params[:food_id])
      render :new
    end
  end
  
  def index
    if params[:name] 
      @foods = Food.all.search(params[:name])
    else
      @foods = Food.all
    end

  end

  def show
    @food = Food.find(params[:id])
  end

  def edit
    @foodlog = @food.foodlogs.build
    @food = current_user.foods.find_by_id(params[:id])
  end

  def update
    @food = current_user.foods.find(params[:id])
    @food.update(food_params)
    if params[:meal_id] && @meal = Meal.find_by_id(params[:meal_id])
      redirect_to meal_path(@meal)
    else
      redirect_to food_path(@food)
    end 
  end

  def destroy
    @food = current_user.foods.find_by_id(params[:id])
    # superpower, scope to admin only
    Foodlog.find_by(food_id: food.id).destroy
    @food.destroy
    
    redirect_to foods_path
  end

  
  private

  def food_params
    params.require(:food).permit(
      :name, :category, :carbs, :fats, :proteins, :calories, 
      foodlogs_attributes: [:quantity, :meal_id, :food_id])
  end

  def find_foods
    @food = current_user.foods.find_by_id(params[:id])
  end

  def redirect_if_not_owner
    if @food.user != current_user
      redirect_to user_path(current_user), alert: "You do not have permission to edit this"
    end
  end

end

app/helpers/foods_helper.rb
module FoodsHelper
end

app/views/foods/_form.html.erb
<%= render partial:'/shared/errors', locals: {obj: @food} %>
<%= render partial:'/shared/errors', locals: {obj: @meal} if @meal %>

<%= form_for [@meal, @food] do |f| %>

  <%= f.label :name %>
  <%= f.text_field :name, placeholder: "Name" %> <br>

  <%= f.label :category %>
  <%= f.select :category, options_for_select(["Dairy", "Fruit", "Grain", "Oil", "Protein", "Vegetable", "Other"]) %><br>

  <%= f.label :carbs %>
  <%= f.number_field :carbs, in: 0..150, step: 1, value: 0%> <br>
  <%= f.label :fats %>
  <%= f.number_field :fats, in: 0..150, step: 1, value: 0 %> <br>
  <%= f.label :proteins %>
  <%= f.number_field :proteins, in: 0..150, step: 1, value: 0 %> <br>

  <%= f.label :calories %>
  <%= f.number_field :calories, in: 0..500, step: 1, value: 0 %> <br>

  <%= f.fields_for :foodlogs, @foodlog do |f|%>

    <%= f.label :quantity %>
    <%= f.number_field :quantity, in: 1..20, step: 1, value: 1 %> <br>
    
    <%= f.hidden_field :meal_id, :value=> @meal.id %>

  <% end%>
  
  <%= f.submit %>

<% end %>

app/views/foods/edit.html.erb
<h2>Edit:</h2>
<%# render 'form' %>


<%= form_for [@meal, @food] do |f| %>

  <%= f.label :name %>
  <%= f.text_field :name %> <br>

  <%= f.label :category %>
  <%= f.select :category, options_for_select(["Dairy", "Fruit", "Grain", "Oil", "Protein", "Vegetable", "Other"]) %><br>

  <%= f.label :carbs %>
  <%= f.number_field :carbs, in: 0..150, step: 1 %> <br>
  <%= f.label :fats %>
  <%= f.number_field :fats, in: 0..150, step: 1 %> <br>
  <%= f.label :proteins %>
  <%= f.number_field :proteins, in: 0..150, step: 1 %> <br>

  <%= f.label :calories %>
  <%= f.number_field :calories, in: 0..500, step: 1 %> <br>
  
  <%= f.submit %>

<% end %>
<br>
<%# button_to "Delete Food", food_path(@food), method: :delete %>

app/views/foods/index.html.erb
  <h2>All of the Foods</h2>

  <%= link_to 'Create Food', new_food_path(@food) %>
  
  <br>

<%= form_tag(foods_path, method: :get) do %>
  <%= label_tag :name %>
  <%= text_field_tag :name %>
  <%= submit_tag %>
<% end %>

<ul>
  <% @foods.each do |food| %>
    <% if current_user.admin %>
      <li><%= link_to "Edit #{food.name}", food_path(food) %></li>
    <% else %>
      <li><%= link_to "#{food.name.titleize}", food_path(food) %></li>
    <% end %>
  <% end %>
</ul>

app/views/foods/new.html.erb
<h2>New:</h2>

<%= render 'form' %>

app/views/foods/show.html.erb
<ul>
<h3><%=  @food.name.titleize %></h3>
  <li> Category: <%=  @food.category %> </li>
  <li> Carbs: <%=  @food.carbs %> </li> 
  <li> Proteins: <%=  @food.proteins %> </li> 
  <li> Fats: <%=  @food.fats %> </li> 
  <li> Calories: <%=  @food.calories %> </li> 
</ul>

<% if  current_user.foods.include?(@food) %>
  <%= link_to 'Edit Food', edit_food_path(@food) %>
<% end %>