config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root 'sessions#home'

  resources :foods
  resources :meals do 
    resources :foods, only: [:new, :create]
    resources :foodlogs, only: [:edit, :update]
  end
  resources :foodlogs
  resources :users, only: %i[new create edit show update destroy] do 
    resources :meals, only: %i[index show]
  end

  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  
  delete '/logout', to: 'sessions#destroy'

  # custom route for scoped items
  # get 'meals/fatty', to: 'meals#fatty', as: 'fatty_meal'

  # match '/auth/:provider/callback', to: 'sessions#create', via: [:get, :post]
  get '/auth/:provider/callback', to: 'sessions#omniauth'
 
  get '*path', to: redirect { '/' }

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Iaso</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
  </head>

  <header>
    <div class="w3-container">
      <div class="w3-bar w3-border w3-light-grey">
        <a class="w3-bar-item w3-button" href="<%= root_url %>">Home</a>
        <% if logged_in? %>
          <li class="w3-bar-item w3-button"><%= link_to "#{current_user.name.titleize}'s Profile", user_path(current_user) %></li>
          <li class="w3-bar-item w3-button"><%= link_to "Meals", user_meals_path(current_user) %></li>
          <li class="w3-bar-item w3-button"><%= link_to "Foods", foods_path %></li>
          <li class="w3-bar-item w3-button"><%= link_to "Log Out", logout_path, method: :delete %></li>
        <% else %>
          <li class="w3-bar-item w3-button"><%= link_to "Sign Up", signup_path %></li>
          <li class="w3-bar-item w3-button"><%= link_to "Log In", login_path %></li>
          <li class="w3-bar-item w3-button"><%= button_to "Log in with Google", '/auth/google_oauth2' %></li>
        <% end %>
      </div>
    </div>
  </header>

  <body>
    <div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <!--<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button> -->
        
        

        </div>
        <div class="navbar-collapse collapse">
          <ul class="nav navbar-nav">

          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </div>

    <!-- content -->

        <hr>

    <% if flash[:alert] %>
      <div class="field_with_errors"><%= flash[:alert] %></div>
    <% end %>

    <% if !!flash[:message] %>
      <div>
        <p><%= flash[:message] %></p>
      </div>
    <% end %>


    <div class="container"  role="main">
      <%= yield %>
    </div>
  </body>
</html>